# Generated by Django 4.2.5 on 2023-12-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_courseexam_examination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
        ),
    ]
